---
title: "Estimate number of publication containing NAPIs"
author: "Pablo Porras"
date: "04/04/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,eval=TRUE)
```

## Summary

Check and estimate how many publications may contain NAPIs in the DSP pipeline output.  

#### Libraries
```{r libraries,message=FALSE,warning=FALSE}
library(data.table)
library(splitstackshape)
library(ggplot2)
```

### Upload lists
#### Full DSP pair-publication list
```{r dsp_comp}
setwd("../dsp_comparison/results/")
system("tar -zxvf pubpaircomp_table_final.txt.tar.gz")
tm_pairs_pmids <- fread(
        "pubpaircomp_table_final.txt",
        header=T,
        sep="\t",
        colClasses="character",
        check.names = T,
        stringsAsFactors = F)
system("rm pubpaircomp_table_final.txt")
setwd("../../dsp_lists/")
```

#### Reference methods to detect NAPIs
```{r napi_mets}
# This list was generated by searching for interactions including NNAAs in Intact and then extracting methods only and qualifying them. 
# napi_mets_mitab <- fread(
#   "./source/NAP_detmets.txt",
#   header = T,
#   colClasses = "character",
#   sep = "\t",
#   stringsAsFactors = F,
#   check.names = T
# )
# 
# napi_mets_mitab <- napi_mets_mitab[,.(
#   NA.specific,
#   Interaction.detection.method.s.,
#   idm_term = gsub("\\)","",gsub(".*\\(","",Interaction.detection.method.s.))
# )]

dsp_met_annots <- unique(tm_pairs_pmids[,.(tm_method_term)])
dsp_met_list <- unique(cSplit(
  dsp_met_annots,
  splitCols = "tm_method_term",
  sep = "|",
  direction = "long",
  drop = F
))

dsp_met_list <- dsp_met_list[,.(
  tm_method_term_clean = tolower(gsub("_.*","",tm_method_term))
)]
dsp_met_list <- unique(dsp_met_list[order(tm_method_term_clean)])
fwrite(
  dsp_met_list,
  "./results/dsp_met_list.txt",
  col.names = T,
  row.names = F,
  quote = F,
  sep = "\t"
)

dsp_met_list_qual <- fread(
  "./results/NAPI_detmets_dsp.txt",
  header = T,
  colClasses = "character",
  stringsAsFactors = F,
  sep = "\t",
  check.names = T
)

napi_mets <- unique(dsp_met_list_qual[NA.specific=="y"]$tm_method_term_clean)
```

### Select records containing NAPI-detecting methods
```{r NAPI_sel}
dsp_napi_raw <- tm_pairs_pmids[grepl(paste(napi_mets,collapse = "|"),tm_method_term)]
dsp_napi_pmids_mets <- unique(dsp_napi_raw[,.(
  pmid,
  tm_method_term
)])

dsp_napi_pmids_mets_list <- unique(cSplit(
  dsp_napi_pmids_mets,
  splitCols = "tm_method_term",
  sep = "|",
  direction = "long",
  drop = F
))

dsp_napi_pmids_mets_list <- dsp_napi_pmids_mets_list[,tm_method_term_clean:=tolower(gsub("_.*","",tm_method_term))]

# Upload simplified terminology
napi_mets_simple <- fread(
  "./results/NAPI_detmets_simple.txt",
  header = T,
  sep = "\t",
  colClasses = "character",
  stringsAsFactors = F,
  check.names = T
)

dsp_napi_pmids_mets_simple <- unique(merge(
  dsp_napi_pmids_mets_list[tm_method_term!=""],
  napi_mets_simple,
  by = "tm_method_term_clean",
  all.x = T,
  all.y = F
))

dsp_napi_pmids_mets_lean <- unique(dsp_napi_pmids_mets_simple[!is.na(term_simple),.(
  pmid,
  term_simple
)])

dsp_napi_counts <- data.table(table(dsp_napi_pmids_mets_lean$term_simple))
colnames(dsp_napi_counts) <- c("NAPI_det_met","nr_pubs")
```

#### Plot
```{r plot_napi,message=F,warning=F,echo=F}
g <- ggplot(dsp_napi_counts,aes(x=reorder(NAPI_det_met,-nr_pubs),y=nr_pubs,fill = NAPI_det_met,label = nr_pubs))
g <- g + geom_bar(stat="identity")
g <- g + geom_text(size = 5, position = position_stack(vjust = 0.5))
g <- g + guides(fill=FALSE)
g <- g + xlab("NAPI detection method")
g <- g + ylab("Number of publications")
g <- g + theme(plot.title = element_text(),
                 panel.grid.major = element_blank(),
                 panel.grid.minor = element_blank(),
                 panel.background = element_blank(),
                 axis.text = element_text(size=14),
                 axis.title.y = element_text(size=18),
                 axis.title.x = element_text(size=18),
                 axis.line = element_line())
g
```



